---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build-image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  # wait for docker service to be up before running docker build
  - n=0; while [ "$n" -lt 60 ] && [ ! -e /var/run/docker.sock ]; do n=$(( n + 1 )); sleep 1; done
  - docker pull quay.io/ukhomeofficedigital/logstash:8.6.0-opensearch-alpha1
  when:
    event: push

- name: scan-image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  depends_on:
    - build-image
  environment:
    IMAGE_NAME: quay.io/ukhomeofficedigital/logstash:8.6.0-opensearch-alpha1
  when:
    event: push

- name: publish-tag
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/logstash
    tags: ${DRONE_TAG}
  environment:
    DOCKER_USERNAME: ukhomeofficedigital+logstash
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  when:
    event:
    - tag

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

- name: anchore-submission-server
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  commands:
    - /run.sh server
...
